apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-threeds
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cosmos-fraud-detection.serviceLabels" (list . "threeds-service") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "cosmos-fraud-detection.serviceSelectorLabels" (list . "threeds-service") | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
