package com.cosmos.fraud.ingestion.mapper;

import com.cosmos.fraud.avro.Channel;
import com.cosmos.fraud.avro.FraudDecision;
import com.cosmos.fraud.avro.Location;
import com.cosmos.fraud.avro.TransactionEvent;
import com.cosmos.fraud.common.dto.ScoringResponse;
import com.cosmos.fraud.common.dto.TransactionRequest;

import java.time.Instant;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Static mapper between API DTOs and Avro generated classes.
 */
public final class TransactionMapper {

    private TransactionMapper() {
    }

    /**
     * Converts a {@link TransactionRequest} DTO and a generated transaction ID into an
     * Avro {@link TransactionEvent} ready for Kafka publishing.
     *
     * @param request the validated inbound request
     * @param txId    the unique transaction identifier generated by {@link com.cosmos.fraud.common.util.IdGenerator}
     * @return a fully populated {@link TransactionEvent}
     */
    public static TransactionEvent toAvroEvent(TransactionRequest request, String txId) {
        Location location = Location.newBuilder()
                .setLat(request.latitude() != null ? request.latitude() : 0.0)
                .setLon(request.longitude() != null ? request.longitude() : 0.0)
                .setCountry(request.country())
                .build();

        Channel channel;
        try {
            channel = Channel.valueOf(request.channel().toUpperCase());
        } catch (IllegalArgumentException ex) {
            channel = Channel.ECOM;
        }

        return TransactionEvent.newBuilder()
                .setTxId(txId)
                .setCardId(request.cardId())
                .setMerchantId(request.merchantId())
                .setAmount(request.amount().doubleValue())
                .setCurrency(request.currency())
                .setMcc(request.mcc())
                .setChannel(channel)
                .setLocation(location)
                .setDeviceFingerprint(request.deviceFingerprint())
                .setTimestamp(Instant.now().toEpochMilli())
                .build();
    }

    /**
     * Converts an Avro {@link FraudDecision} received from the scoring service into
     * the API-level {@link ScoringResponse} DTO.
     *
     * @param decision the Avro decision received from the scoring topic
     * @return a {@link ScoringResponse} with all relevant fields populated
     */
    public static ScoringResponse toScoringResponse(FraudDecision decision) {
        List<String> appliedRules = decision.getAppliedRules() != null
                ? decision.getAppliedRules().stream()
                        .map(CharSequence::toString)
                        .collect(Collectors.toList())
                : List.of();

        return new ScoringResponse(
                decision.getTxId().toString(),
                decision.getRiskScore(),
                decision.getDecision().name(),
                appliedRules,
                decision.getLatencyMs()
        );
    }
}
