server:
  port: 8084

spring:
  application:
    name: threeds-service

scoring:
  service:
    url: http://localhost:8083

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: INFO
    com.cosmos.fraud.threeds: DEBUG
